### ISSUE TITLE
you are asking for @"_isLastItem" and @"_isFirstItem" but they are not defined, set, or computed anwhere?

### ISSUE THREAD

**Issue by hamin** [iluuu1994/Pathbar#1]
This is in ITPathbarComponentCell.m . Fails the build on the sample app. Super cool project, I need something like this. Would be great to see this fixed. Thanks again.

**Comment by iluuu1994** [comment]
Hi Amin

NSPathControl is poorly written. It has no methods to override so you can adjust the design.
Therefore I had to access private methods and variables.

Look up 'class dump' and you'll see what I mean.

Via  
[[self valueForKey:@"_isLastItem"] boolValue];
you should actually have no problem compiling it. It would rather give you a run-time exception.
What error message do you get?  

Ilija

**Comment by hamin** [comment]
You're right it is a runtime error:

[<ITPathbarComponentCell 0x100503990> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _isLastItem.

**Comment by iluuu1994** [comment]
Ok, what OS X SKD are you using? Mountain Lion?

**Comment by hamin** [comment]
@iluuu1994 i'm using Lion still, the latest 10.7.x

**Comment by iluuu1994** [comment]
I actually haven't tested it on Lion.
Try using this workaround.  

Replace the two methods `isLastItem` and `isFirstItem`.
- (BOOL)isLastItem {  
  NSArray *cells = [(ITPathbar *)[self controlView] pathComponentCells];
  return ([cells lastObject] == self);
  }
- (BOOL)isFirstItem {  
  NSArray *cells = [(ITPathbar *)[self controlView] pathComponentCells];
  return (cells[0] == self);
  }

**Comment by hamin** [comment]
Hey, that worked. Of course I had to add

``` objective-c
#import "ITPathbar.h"
```

to the implementation. Thanks!

**Comment by iluuu1994** [comment]
Thanks for your help, I'll update the project and add this as a workaround. The only downside is that this wouldn't work with NSURLs anymore.

**Comment by hamin** [comment]
@iluuu1994 no no, thank you! Works really well, I'm going to try to use it in a project of mine. Thanks for your hard work!

**Comment by iluuu1994** [comment]
Well, your welcome! No hard work, just a little research ;)
